// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXggnm3OswlCYDWUmC94EV_98J09TlKP0',
    appId: '1:792437430026:web:c3a12a0757d7a237f3ccf3',
    messagingSenderId: '792437430026',
    projectId: 'joyful-journey-4f3bf',
    authDomain: 'joyful-journey-4f3bf.firebaseapp.com',
    storageBucket: 'joyful-journey-4f3bf.appspot.com',
    measurementId: 'G-RYVDT34CMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6SI8y147a5TL0HOoC_EqaJc7IQ8pH49g',
    appId: '1:792437430026:android:d01a9c768788c1e4f3ccf3',
    messagingSenderId: '792437430026',
    projectId: 'joyful-journey-4f3bf',
    storageBucket: 'joyful-journey-4f3bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxK7ni_qVGQBYsg6SL6kBWkSJFQgTbafY',
    appId: '1:792437430026:ios:c0890947e536f9c3f3ccf3',
    messagingSenderId: '792437430026',
    projectId: 'joyful-journey-4f3bf',
    storageBucket: 'joyful-journey-4f3bf.appspot.com',
    iosBundleId: 'com.example.joyfulJourney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxK7ni_qVGQBYsg6SL6kBWkSJFQgTbafY',
    appId: '1:792437430026:ios:c0890947e536f9c3f3ccf3',
    messagingSenderId: '792437430026',
    projectId: 'joyful-journey-4f3bf',
    storageBucket: 'joyful-journey-4f3bf.appspot.com',
    iosBundleId: 'com.example.joyfulJourney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXggnm3OswlCYDWUmC94EV_98J09TlKP0',
    appId: '1:792437430026:web:a0438a79d258beccf3ccf3',
    messagingSenderId: '792437430026',
    projectId: 'joyful-journey-4f3bf',
    authDomain: 'joyful-journey-4f3bf.firebaseapp.com',
    storageBucket: 'joyful-journey-4f3bf.appspot.com',
    measurementId: 'G-L2F2E3G90F',
  );
}
